"""Added account_type to Customers

Revision ID: 78604d2ad2ae
Revises: 
Create Date: 2026-03-09 15:58:49.273936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78604d2ad2ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('account_type')

    # ### end Alembic commands ###
